language: php
php:
  - '7.0'
  - '7.1'

sudo: required

before_install:
  - sudo apt-get -qq update

install:
  - cd test
  - npm install
  - cd ..

script:
  - echo $DRINK_SERVER_URL
  - echo $RATE_LIMIT_DROPS_DROP
  - phpunit test/build_tests.php

notifications:
    on_success: never
    on_failure: never